"use client";

import { useEffect, useState } from "react";
import { format, startOfMonth } from "date-fns";
import { toZonedTime } from "date-fns-tz";
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, Info, RotateCcw, UserRound, Users, XCircle } from "lucide-react";
import { CLINIC_TZ } from "@/lib/tz";

/* eslint-disable react-hooks/set-state-in-effect */

type Physio = { id: string; full_name: string; is_active: boolean };
type Report = { metrics: { total: number; completed: number; cancelled: number; noShows: number; newPatients: number }; statuses: Array<{ status: string; label: string; count: number; percentage: number }>; summary: Array<{ date: string; total: number; completed: number; cancelled: number; no_show: number; scheduled: number }>; detailed: Array<{ id: string; starts_at: string; ends_at: string; status: string; reason_for_visit: string | null; patient: { full_name: string | null; email: string; phone: string | null } | null; physiotherapists: { full_name: string } | null }>; totalDetailed: number; timezone: string };
const today = toZonedTime(new Date(), CLINIC_TZ);
const initialFrom = format(startOfMonth(today), "yyyy-MM-dd");
const initialTo = format(today, "yyyy-MM-dd");
const statusLabel: Record<string, string> = { confirmed: "Confirmed", rescheduled: "Rescheduled", completed: "Completed", cancelled: "Cancelled", no_show: "No-show" };

export default function AdminReportsPage() {
  const [from, setFrom] = useState(initialFrom); const [to, setTo] = useState(initialTo); const [physioId, setPhysioId] = useState(""); const [status, setStatus] = useState(""); const [physios, setPhysios] = useState<Physio[]>([]); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [page, setPage] = useState(1);
  const query = new URLSearchParams({ dateFrom: from, dateTo: to }); if (physioId) query.set("physioId", physioId); if (status) query.set("status", status);
  function load() { if (to < from) { setError(true); setLoading(false); return; } setLoading(true); setError(false); fetch(`/api/admin/reports?${query}`).then((res) => { if (!res.ok) throw new Error(); return res.json(); }).then((data) => { setReport(data); setPage(1); }).catch(() => { setReport(null); setError(true); }).finally(() => setLoading(false)); }
  useEffect(() => { fetch("/api/admin/physiotherapists").then((res) => res.json()).then((data) => setPhysios(data.physiotherapists ?? [])); }, []);
  // Report data is intentionally refreshed whenever the shared filter state changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [from, to, physioId, status]);
  function reset() { setFrom(initialFrom); setTo(initialTo); setPhysioId(""); setStatus(""); }
  const exportHref = `/api/admin/export?${query}`;
  const detailed = report?.detailed.slice((page - 1) * 5, page * 5) ?? [];
  const totalPages = Math.max(1, Math.ceil((report?.totalDetailed ?? 0) / 5));

  return <main className="mx-auto w-full max-w-[1180px] pb-8"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-[#e1e8eb] pb-5"><div><h1 className="text-[28px] font-bold tracking-[-0.025em] text-[#183247]">Reports</h1><p className="mt-1 text-[12px] text-[#718596]">View and export appointment and clinic activity.</p></div><div className="flex items-center gap-2 rounded-[8px] border border-[#dce5e9] bg-white px-3 py-2"><Clock3 className="h-4 w-4 text-[#168884]" aria-hidden="true" /><span className="text-[10px] font-semibold text-[#536c7b]">{CLINIC_TZ}</span></div></header>
    <section className="mt-5 rounded-[9px] border border-[#dce5e9] bg-white p-4"><div className="grid gap-2 md:grid-cols-[1.2fr_1fr_1fr_auto_auto]"><label className="text-[10px] font-semibold text-[#50697b]">Date range<span className="mt-1 flex items-center gap-2 rounded-[7px] border border-[#dce5e9] px-2"><CalendarDays className="h-3.5 w-3.5" /><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="h-8 min-w-0 flex-1 text-[10px] outline-none" /><span>-</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="h-8 min-w-0 flex-1 text-[10px] outline-none" /></span></label><label className="text-[10px] font-semibold text-[#50697b]">Physiotherapist<select aria-label="Filter by physiotherapist" value={physioId} onChange={(event) => setPhysioId(event.target.value)} className="mt-1 h-10 w-full rounded-[7px] border border-[#dce5e9] px-3 text-[10px]"><option value="">All Physiotherapists</option>{physios.map((physio) => <option key={physio.id} value={physio.id}>{physio.full_name}</option>)}</select></label><label className="text-[10px] font-semibold text-[#50697b]">Status<select aria-label="Filter by appointment status" value={status} onChange={(event) => setStatus(event.target.value)} className="mt-1 h-10 w-full rounded-[7px] border border-[#dce5e9] px-3 text-[10px]"><option value="">All Statuses</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="button" onClick={reset} className="mt-4 flex h-10 items-center justify-center gap-1 rounded-[7px] border border-[#dce5e9] px-3 text-[10px] font-semibold text-[#536c7b]"><RotateCcw className="h-3 w-3" />Reset</button><a href={exportHref} className="mt-4 flex h-10 items-center justify-center gap-1 rounded-[7px] bg-[#107f7b] px-4 text-[10px] font-semibold text-white"><Download className="h-3.5 w-3.5" />Export Report</a></div>{to < from && <p className="mt-2 text-[10px] text-[#b33c38]">End date must be on or after the start date.</p>}</section>
    {loading && <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[1, 2, 3, 4, 5].map((item) => <div key={item} className="h-24 animate-pulse rounded-[9px] bg-[#f0f4f5]" />)}</div>}{error && !loading && <div className="mt-5 rounded-[9px] border border-[#edc8c5] bg-[#fff5f4] p-6 text-center text-[12px] text-[#b33c38]">Couldn&apos;t load this report. <button type="button" onClick={load} className="font-semibold underline">Try again</button></div>}{report && !loading && !error && <><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total Appointments" value={report.metrics.total} icon={<CalendarDays />} tone="teal" /><Metric label="Completed" value={report.metrics.completed} icon={<CheckCircle2 />} tone="green" /><Metric label="Cancelled" value={report.metrics.cancelled} icon={<XCircle />} tone="blue" /><Metric label="No-shows" value={report.metrics.noShows} icon={<UserRound />} tone="orange" /><Metric label="New Patients" value={report.metrics.newPatients} icon={<Users />} tone="purple" /></div><div className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,.9fr)]"><div className="space-y-4"><Summary summary={report.summary} /><Detailed rows={detailed} page={page} totalPages={totalPages} total={report.totalDetailed} onPrevious={() => setPage((value) => value - 1)} onNext={() => setPage((value) => value + 1)} /></div><div className="space-y-4"><StatusChart statuses={report.statuses} total={report.metrics.total} /><TrendChart summary={report.summary} /></div></div><div className="mt-4 flex items-center gap-2 rounded-[7px] bg-[#f1f6f7] px-3 py-2 text-[10px] text-[#617988]"><Info className="h-3.5 w-3.5 text-[#168884]" />All dates and times are shown in {report.timezone}.</div></>}</main>;
}
function Metric({ label, value, icon, tone }: { label: string; value: number; icon: React.ReactNode; tone: string }) { return <div className="rounded-[9px] border border-[#e1e8eb] bg-white p-4 shadow-[0_2px_8px_rgba(14,17,22,0.04)]"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${tone}`} aria-hidden="true">{icon}</span><div><p className="text-[10px] font-semibold text-[#718596]">{label}</p><p className="mt-1 text-[23px] font-bold tabular-nums text-[#19364c]">{value}</p></div></div></div>; }
function Summary({ summary }: { summary: Report["summary"] }) { return <section className="overflow-hidden rounded-[9px] border border-[#e1e8eb] bg-white"><div className="border-b border-[#edf1f2] px-4 py-3"><h2 className="text-[13px] font-bold text-[#19364c]">Appointments Summary</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-[10px]"><thead className="bg-[#fbfcfc] text-[9px] text-[#718596]"><tr><th className="px-4 py-3">Date</th><th>Total</th><th>Completed</th><th>Cancelled</th><th>No-shows</th><th>Scheduled</th></tr></thead><tbody>{summary.length ? summary.map((row) => <tr key={row.date} className="border-t border-[#edf1f2]"><td className="px-4 py-2 font-semibold">{format(new Date(`${row.date}T00:00:00`), "EEE, d MMM yyyy")}</td><td>{row.total}</td><td className="text-[#168884]">{row.completed}</td><td className="text-[#c64a47]">{row.cancelled}</td><td className="text-[#c67a2c]">{row.no_show}</td><td>{row.scheduled}</td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-[#81939e]">No appointments in this range.</td></tr>}</tbody></table></div></section>; }
function Detailed({ rows, page, totalPages, total, onPrevious, onNext }: { rows: Report["detailed"]; page: number; totalPages: number; total: number; onPrevious: () => void; onNext: () => void }) { return <section className="overflow-hidden rounded-[9px] border border-[#e1e8eb] bg-white"><div className="border-b border-[#edf1f2] px-4 py-3"><h2 className="text-[13px] font-bold text-[#19364c]">Detailed Appointments</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="bg-[#fbfcfc] text-[9px] text-[#718596]"><tr><th className="px-4 py-3">Time</th><th>Patient</th><th>Physiotherapist</th><th>Reason</th><th>Status</th><th>Duration</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t border-[#edf1f2]"><td className="px-4 py-2 tabular-nums">{format(toZonedTime(new Date(row.starts_at), CLINIC_TZ), "dd MMM, HH:mm")}</td><td className="font-semibold">{row.patient?.full_name ?? "Patient"}</td><td>{row.physiotherapists?.full_name ?? "—"}</td><td className="max-w-[120px] truncate" title={row.reason_for_visit ?? undefined}>{row.reason_for_visit ?? "—"}</td><td><span className="rounded bg-[#f1f6f7] px-1.5 py-1 text-[9px]">{statusLabel[row.status] ?? row.status}</span></td><td>{Math.round((new Date(row.ends_at).getTime() - new Date(row.starts_at).getTime()) / 60000)} min</td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-[#81939e]">No appointments match these filters.</td></tr>}</tbody></table></div>{rows.length > 0 && <div className="flex items-center justify-between border-t border-[#edf1f2] px-4 py-3 text-[10px] text-[#718596]"><span>Showing {((page - 1) * 5) + 1} to {Math.min(page * 5, total)} of {total}</span><span className="flex items-center gap-2"><button type="button" aria-label="Previous page" disabled={page <= 1} onClick={onPrevious} className="h-7 w-7 rounded border disabled:opacity-35"><ChevronLeft className="mx-auto h-3.5 w-3.5" /></button>{page} / {totalPages}<button type="button" aria-label="Next page" disabled={page >= totalPages} onClick={onNext} className="h-7 w-7 rounded border disabled:opacity-35"><ChevronRight className="mx-auto h-3.5 w-3.5" /></button></span></div>}</section>; }
function StatusChart({ statuses, total }: { statuses: Report["statuses"]; total: number }) { return <section className="rounded-[9px] border border-[#e1e8eb] bg-white p-4"><h2 className="text-[13px] font-bold text-[#19364c]">Appointments by Status</h2>{total === 0 ? <p className="py-12 text-center text-[11px] text-[#81939e]">No status data for this range.</p> : <div className="mt-4 flex items-center gap-5"><div className="h-32 w-32 shrink-0 rounded-full" style={{ background: `conic-gradient(#0e9f83 0 ${(statuses.find((item) => item.status === "completed")?.percentage ?? 0)}%, #e34343 0 ${(statuses.filter((item) => ["completed", "cancelled"].includes(item.status)).reduce((sum, item) => sum + item.percentage, 0))}%, #d68b25 0 ${(statuses.filter((item) => ["completed", "cancelled", "no_show"].includes(item.status)).reduce((sum, item) => sum + item.percentage, 0))}%, #7b54c5 0 100%)` }} aria-label="Appointment status distribution" /><div className="space-y-2 text-[10px]">{statuses.map((item) => <div key={item.status} className="flex items-center justify-between gap-4"><span><span className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#168884]" />{item.label}</span><strong>{item.count} ({item.percentage}%)</strong></div>)}<p className="border-t pt-2 font-semibold">Total {total}</p></div></div>}</section>; }
function TrendChart({ summary }: { summary: Report["summary"] }) { const points = summary.slice(-14); const max = Math.max(1, ...points.map((item) => item.total)); return <section className="rounded-[9px] border border-[#e1e8eb] bg-white p-4"><h2 className="text-[13px] font-bold text-[#19364c]">Appointments Trend</h2>{points.length === 0 ? <p className="py-12 text-center text-[11px] text-[#81939e]">No trend data for this range.</p> : <div className="mt-4"><div className="flex h-32 items-end gap-1 border-b border-l border-[#edf1f2] px-2">{points.map((item) => <div key={item.date} className="group relative flex h-full flex-1 items-end"><span className="w-full rounded-t bg-[#168884]" style={{ height: `${Math.max(4, (item.total / max) * 100)}%` }} title={`${item.date}: ${item.total} appointments`} /></div>)}</div><div className="mt-2 flex justify-between text-[8px] text-[#81939e]"><span>{points[0].date}</span><span>{points[points.length - 1].date}</span></div><p className="mt-3 text-[9px] text-[#718596]"><span className="mr-1 inline-block h-2 w-2 rounded-full bg-[#168884]" />Total appointments per day</p></div>}</section>; }

/* eslint-enable react-hooks/set-state-in-effect */
